id             = "new-darcula"
name           = "New Darcula Theme"
description    = "ðŸ”® Ultra clean and minimal take on the JetBrains Darcula theme.\nIncludes dark, darker, and light variants."
version        = "1.0.8"
authors        = ["Evan Simpson <evan@evan.news>"]
repository     = "https://github.com/e-simpson/new-darcula-z"
schema_version = 1
